export const Countries = {
		"Afghanistan": [],
		"Afrique du Sud": [],
		"Albanie": [],
		"Algérie": [],
		"Allemagne": [],
		"Andorre": [],
		"Angola": [],
		"Anguilla": [],
		"Antarctique": [],
		"Antigua-et-Barbuda": [],
		"Antilles néerlandaises": [],
		"Arabie saoudite": [],
		"Argentine": [],
		"Arménie": [],
		"Aruba": [],
		"Australie": [],
		"Autriche": [],
		"Azerbaïdjan": [],
		"Bahamas": [],
		"Bahreïn": [],
		"Bangladesh": [],
		"Barbade": [],
		"Bélarus": [],
		"Belgique": [
		    "Alost",
		    "Andenne",
		    "Antoing",
		    "Anvers",
		    "Arlon",
		    "Ath",
		    "Aubange",
		    "Audenarde",
		    "Beauraing",
		    "Beringen",
		    "Bilzen",
		    "Binche",
		    "Blankenberge",
		    "Braine-le-Comte",
		    "Bruges",
		    "Chièvres",
		    "Chimay",
		    "Chiny",
		    "Ciney",
		    "Comines-Warneton",
		    "Courtrai",
		    "Couvin",
		    "Deinze",
		    "Diest",
		    "Dilsen-Stokkem",
		    "Dinant",
		    "Dixmude",
		    "Durbuy",
		    "Enghien",
		    "Eupen",
		    "Florenville",
		    "Fontaine-l'Évêque",
		    "Fosses-la-Ville",
		    "Furnes",
		    "Geel",
		    "Gembloux",
		    "Genappe",
		    "Genk",
		    "Gistel",
		    "Hamont-Achel",
		    "Hannut",
		    "Harelbeke",
		    "Hasselt",
		    "Herck-la-Ville",
		    "Herentals",
		    "Herstal",
		    "Herve",
		    "Hoogstraten",
		    "Houffalize",
		    "Huy",
		    "La Roche-en-Ardenne",
		    "Landen",
		    "Léau",
		    "Le Rœulx",
		    "Lessines",
		    "Leuze-en-Hainaut",
		    "Liège",
		    "Lokeren",
		    "Lommel",
		    "Looz",
		    "Lo-Reninge",
		    "Louvain",
		    "Malines",
		    "Malmedy",
		    "Marche-en-Famenne",
		    "Menin",
		    "Mons",
		    "Montaigu-Zichem",
		    "Mortsel",
		    "Mouscron",
		    "Ninove",
		    "Nivelles",
		    "Ottignies-Louvain-la-Neuve",
		    "Oudenburg",
		    "Philippeville",
		    "Poperinge",
		    "Roulers",
		    "Saint-Trond",
		    "Saint-Vith",
		    "Seraing",
		    "Soignies",
		    "Stavelot",
		    "Thourout",
		    "Thuin",
		    "Tielt",
		    "Tirlemont",
		    "Tongres",
		    "Tournai",
		    "Tubize",
		    "Turnhout",
		    "Vilvorde",
		    "Virton",
		    "Visé",
		    "Waregem",
		    "Waremme",
		    "Wavre",
		    "Wervicq",
		],
		"Belize": [],
	"Bénin": [
		"Cotonou",
		"Abomey-Calavi",
		"Porto-Novo",
		"Parakou",
		"Djougou",
		"Bohicon",
		"Natitingou",
		"Savé",
		"Abomey",
		"Nikki",
		"Lokossa",
		"Ouidah",
		"Dogbo-Tota",
		"Kandi",
		"Cové",
		"Malanville",
		"Pobé",
		"Kérou",
		"Savalou",
		"Sakété",
		"Comè",
		"Bembéréké",
		"Bassila",
		"Banikoara",
		"Kétou",
		"Dassa-Zoumè",
		"Tchaourou",
		"Allada",
		"Aplahoué",
		"Tanguiéta",
		"N'Dali",
		"Segbana",
		"Athiémé",
		"Grand Popo",
		"Kouandé",
	],
		"Bermudes": [],
		"Bhoutan": [],
		"Bolivie": [],
		"Bosnie-Herzégovine": [],
		"Botswana": [],
		"Brésil": [],
		"Brunéi Darussalam": [],
		"Bulgarie": [],
		"Burkina Faso": [
			"Boulkiemdé",
			"Comoé",
			"Yatenga",
			"Mouhoun",
			"Sanmatenga",
			"Sanmatenga",
			"Kadiogo",
			"Boulgou",
			"Kouritenga",
			"Gourma",
			"Sanguié",
			"Koulpélogo",
			"Boulgou",
			"Séno",
			"Bam",
			"Boulkiemdé",
			"Sanguié",
			"Tapoa",
			"Tuy",
			"Banwa",
			"Passoré",
			"Soum",
			"Sanguié",
			"Sissili",
			"Kossi",
			"Nahouri",
			"Kouritenga",
			"Ganzourgou",
			"Bazèga",
			"Sourou",
			"Kénédougou",
			"Zondoma",
			"Sourou",
			"Namentenga",
			"Loroum",
			"Zoundwéogo",
			"Kompienga",
			"Balé",
			"Bougouriba",
			"Oubritenga",
			"Ioba",
			"Kourwéogo",
			"Banwa",
		],
		"Burundi": [
			"Bujumbura",
			"Muyinga",
			"Ruyigi",
			"Gitega",
			"Ngozi",
			"Rutana",
			"Bururi",
			"Makamba",
			"Kayanza",
			"Muramvya",
			"Cibitoke",
			"Bubanza",
			"Karuzi",
			"Cankuzo",
			"Kirundo",
			"Rumonge",
			"Mwaro",
		],
		"Cambodge": [],
	"Cameroun": [
		"Douala",
		"Yaoundé",
		"Garoua",
		"Bamenda",
		"Maroua",
		"Nkongsamba",
		"Bafoussam",
		"Ngaoundéré",
		"Bertoua",
		"Loum",
		"Kumba",
		"Edéa",
		"Kumbo",
		"Foumban",
		"Mbouda",
		"Dschang",
		"Limbé",
		"Ebolowa",
		"Kousséri",
		"Guider",
		"Meiganga",
		"Yagoua",
		"Mbalmayo",
		"Bafang",
		"Tiko",
		"Bafia",
		"Wum",
		"Kribi",
		"Buea",
		"Sangmélima",
		"Foumbot",
		"Bangangté",
		"Batouri",
		"Banyo",
		"Nkambé",
		"Bali",
		"Mbanga",
		"Mokolo",
		"Melong",
		"Manjo",
		"GarouaBoulaï",
		"Mora",
		"Kaélé",
		"Tibati",
		"Ndop",
		"Akonolinga",
		"Eséka",
		"Mamfé",
		"Obala",
		"Muyuka",
		"NangaEboko",
		"AbongMbang",
		"Fundong",
		"Nkoteng",
		"Fontem",
		"Mbandjock",
		"Touboro",
		"Ngaoundal",
		"Yokadouma",
		"Pitoa",
		"Tombel",
		"Kékem",
		"Magba",
		"Bélabo",
		"Tonga",
		"Maga",
		"Koutaba",
		"Blangoua",
		"Guidiguis",
		"Bogo",
		"Batibo",
		"Yabassi",
		"Figuil",
		"Makénéné",
		"Gazawa",
		"Tcholliré",
	],
		"Canada": [
			"Beauceville",
			"Bécancour",
			"Belleterre",
			"Berthierville",
			"Bois-des-Filion",
			"Boisbriand",
			"Boucherville",
			"Lac-Brome",
			"Bromont",
			"Brownsburg-Chatham",
			"Cabano",
			"Candiac",
			"Cap-Chat",
			"Cap-Santé",
			"Carleton-sur-Mer",
			"Causapscal",
			"Châteauguay",
			"Château-Richer",
			"Chibougamau",
			"Cookshire-Eaton",
			"Côte-Saint-Luc",
			"Châteauguayonauguay",
			"Chibougamau",
			"Cookshire-Eaton",
			"Côte-Saint-Luc",
			"Châteauguayonauguay",
			"Dolbeau-Mistassini",
			"Dollard-des-Ormeaux",
			"Dorval",
			"Drummondville",
			"Dunham",
			"East Angus",
			"Fermont",
			"Forestville",
			"Fossambault-sur-le-Lac",
			"Gatineau",
			"Gracefield",
			"L'Île-Cadieux",
			"L'Île-Dorval",
			"L'Île-Perrot",
			"Kingsey Falls",
			"Lac-Delage",
			"Lac-Mégantic",
			"Lac-Saint-Joseph",
			"Lac-Sergent",
			"Lachute",
			"L'Ancienne-Lorette",
			"L'Assomption",
			"La Malbaie",
			"La Pocatière",
			"La Prairie",
			"La Sarre",
			"La Tuque",
			"Lavaltrie",
			"Lebel-sur-Quévillon",
			"L'Île-Perrot",
			"Longueuil",
			"Louiseville",
			"Macamic",
			"Magog",
			"Maniwaki",
			"Marieville",
			"Mascouche",
			"Matagami",
			"Métabetchouan–Lac-à-la-Croix",
			"Métis-sur-Mer",
			"Mirabel (Québec)",
			"Mont-Joli",
			"Mont-Laurier",
			"Mont-Saint-Hilaire",
			"Mont-Tremblant",
			"Montréal",
			"Montréal-Est",
			"Montréal-Ouest",
			"Murdochville",
			"New Richmond",
			"Nicolet",
			"Notre-Dame-de-l'Île-Perrot",
			"Notre-Dame-des-Prairies",
			"Notre-Dame-du-Lac",
			"Otterburn Park",
			"Percé",
			"Pincourt",
			"La Pocatière",
			"Pohénégamook",
			"Pointe-Claire",
			"Pont-Rouge",
			"Port-Cartier",
			"La Prairie",
			"Princeville",
			"Rimouski",
			"Rivière-du-Loup",
			"Rivière-Rouge",
			"Rosemère",
			"Rouyn-Noranda",
			"Sainte-Adèle",
			"Sainte-Agathe-des-Monts",
			"Sainte-Anne-de-Beaupré",
			"Sainte-Anne-de-Bellevue",
			"Sainte-Anne-des-Monts",
			"Sainte-Anne-des-Plaines",
			"Saint-Augustin-de-Desmaures",
			"Saint-Basile-le-Grand",
			"Saint-Bruno-de-Montarville",
			"Sainte-Catherine-de-la-Jacques-Cartier",
			"Saint-Césaire",
			"Saint-Constant",
			"Saint-Gabriel",
			"Saint-Hyacinthe",
			"Saint-Jean-sur-Richelieu",
			"Saint-Joseph-de-Beauce",
			"Saint-Joseph-de-Sorel",
			"Saint-Lin-Laurentides",
			"Saint-Marc-des-Carrières",
			"Sainte-Marguerite-du-Lac-Masson",
			"Sainte-Marthe-sur-le-Lac",
			"Saint-Pamphile",
			"Saint-Pascal",
			"Saint-Pie",
			"Saint-Raymond",
			"Sainte-Thérèse",
			"Saint-Tite",
			"Salaberry-de-Valleyfield",
			"La Sarre",
			"Schefferville",
			"Scotstown",
			"Sept-Îles",
			"Shawinigan",
			"Sherbrooke",
			"Sorel-Tracy",
			"Témiscaming",
			"Terrebonne",
			"Thetford Mines",
			"Trois-Pistoles",
			"Trois-Rivières",
			"La Tuque",
			"Val-d'Or",
			"Vaudreuil-Dorion",
			"Victoriaville",
			"Westmount",
		],
		"Cap-Vert": [],
		"Ceuta et Melilla": [],
		"Chili": [],
		"Chine": [],
		"Chypre": [],
		"Colombie": [],
		"Comores": [
			"Moroni",
			"Mutsamudu",
			"Domoni",
			"Fomboni",
			"Tsembéhou",
			"Ongodjou",
			"Sima",
			"Ouani",
			"Mirontsi",
			"Adda Daouéni",
			"Bazmini",
			"Koni Djodjo",
			"Moya",
			"Iconi",
			"Ounkazi",
			"Dindri",
			"Ngandzalé",
			"Mbéni",
			"Mitsamiouli",
			"Barakani",
			"Mbambao Mtsanga",
			"Chandra",
			"Ouellah Hamahamet",
			"Mramani",
			"Mrémani",
			"Koki",
			"Jimlimi",
			"Mvouni",
			"Tsidjé",
			"Foumbouni",
			"Nkourani ya Sima",
			"Magnassini",
			"Mitsoudjé-Troumbeni",
			"Dembéni",
		],
		"Congo-Brazzaville": [
			"Kinshasa",
			"Lubumbashi",
			"Mbuji-Mayi",
			"Kananga",
			"Kisangani",
			"Bukavu",
			"Tshikapa",
			"Kolwezi",
			"Likasi",
			"Goma",
			"Kikwit",
			"Uvira",
			"Bunia",
			"Kalemie",
			"Mbandaka",
			"Matadi",
			"Kabinda",
			"Butembo",
			"Baraka",
			"Mwene-Ditu",
			"Isiro",
			"Kindu",
			"Boma",
			"Kamina",
			"Gandajika",
			"Bandundu",
			"Gemena",
			"Kipushi",
			"Bumba",
			"Mbanza-Ngungu",
		],
		"Corée du Nord": [],
		"Corée du Sud": [],
		"Costa Rica": [],
	"Côte d’Ivoire": [
		"Abidjan",
		"Bouaké",
		"Daloa",
		"Yamoussoukro",
		"San-Pédro",
		"Divo",
		"Korhogo",
		"Anyama",
		"Abengourou",
		"Man",
		"Gagnoa",
		"Soubré",
		"Agboville",
		"Dabou",
		"Grand-Bassam",
		"Bouaflé",
		"Issia",
		"Sinfra",
		"Katiola",
		"Bingerville",
		"Adzopé",
		"Séguéla",
		"Bondoukou",
		"Gôh",
		"Ferkessedougou",
		"Dimbokro",
		"Odienné",
		"Duékoué",
		"Danané",
		"Tingréla",
		"Guiglo",
		"Boundiali",
		"Agnibilékrou",
		"Daoukro",
		"Vavoua",
		"Zuénoula",
		"Tiassalé",
		"Toumodi",
		"Akoupé",
		"Lakota",
	],
		"Croatie": [],
		"Cuba": [],
		"Danemark": [],
		"Diego Garcia": [],
		"Djibouti": [
			"Djibouti",
			"Ali Sabieh",
			"Tadjourah",
			"Obock",
			"Dikhil",
			"Arta",
			"Holl-Holl, Holhol",
			"Dorra",
			"Galafi",
			"Loyada",
			"Alaili Dadda",
		],
		"Dominique": [],
		"Égypte": [],
		"El Salvador": [],
		"Émirats arabes unis": [],
		"Équateur": [],
		"Érythrée": [],
		"Espagne": [],
		"Estonie": [],
		"État de la Cité du Vatican": [],
		"États fédérés de Micronésie": [],
		"États-Unis": [],
		"Éthiopie": [],
		"Fidji": [],
		"Finlande": [],
		"France": [
            "Malakoff (Hauts-de-Seine)|Malakoff",
            "Périgueux",
            "Mont-de-Marsan",
            "Clichy-sous-Bois",
            "Aix-les-Bains",
            "Maubeuge",
            "Vienne (Isère)|Vienne",
            "Sotteville-lès-Rouen",
            "Saint-Étienne-du-Rouvray",
            "Saint-Laurent-du-Var",
            "Soissons",
            "Saumur",
            "Vallauris",
            "Vierzon",
            "Alençon",
            "Aurillac",
            "Le Grand-Quevilly",
            "Montbéliard",
            "Saint-Dizier",
            "Biarritz",
            "Vichy",
            "Orly",
            "Bruay-la-Buissière",
            "Le Creusot",
            "Paris",
            "Marseille",
            "Lyon",
            "Toulouse",
            "Nice",
            "Nantes",
            "Montpellier",
            "Strasbourg",
            "Bordeaux",
            "Lille",
            "Rennes",
            "Reims",
            "Saint-Étienne",
            "Le Havre",
            "Toulon",
            "Grenoble",
            "Dijon",
            "Angers",
            "Nîmes",
            "Villeurbanne",
            "Saint-Denis (La Réunion)|Saint-Denis",
            "Aix-en-Provence",
            "Le Mans",
            "Clermont-Ferrand",
            "Brest",
            "Tours",
            "Amiens",
            "Limoges",
            "Annecy",
            "Perpignan",
            "Boulogne-Billancourt",
            "Metz",
            "Besançon",
            "Orléans",
            "Saint-Denis (Seine-Saint-Denis)|Saint-Denis",
            "Argenteuil (Val-d'Oise)|Argenteuil",
            "Rouen",
            "Mulhouse",
            "Montreuil (Seine-Saint-Denis)|Montreuil",
            "Saint-Paul (La Réunion)|Saint-Paul",
            "Caen",
            "Nancy",
            "Nouméa",
            "Tourcoing",
            "Roubaix",
            "Nanterre",
            "Vitry-sur-Seine",
            "Avignon",
            "Créteil",
            "Dunkerque",
            "Poitiers",
            "Aubervilliers",
            "Asnières-sur-Seine",
            "Colombes",
            "Versailles",
            "Aulnay-sous-Bois",
            "Saint-Pierre (La Réunion)|Saint-Pierre",
            "Courbevoie",
            "Fort-de-France",
            "Cherbourg-en-Cotentin",
            "Rueil-Malmaison",
            "Champigny-sur-Marne",
            "Le Tampon",
            "Pau",
            "Béziers",
            "La Rochelle",
            "Calais",
            "Saint-Maur-des-Fossés",
            "Antibes",
            "Cannes",
            "Mamoudzou",
            "Mérignac (Gironde)|Mérignac",
            "Drancy",
            "Colmar",
            "Saint-Nazaire",
            "Ajaccio",
            "Issy-les-Moulineaux",
            "Évry-Courcouronnes",
            "Noisy-le-Grand",
            "Bourges",
            "Vénissieux",
            "La Seyne-sur-Mer",
            "Cergy",
            "Levallois-Perret",
            "Quimper",
            "Valence (Drôme)|Valence",
            "Villeneuve-d'Ascq",
            "Antony",
            "Pessac",
            "Clichy",
            "Ivry-sur-Seine",
            "Troyes",
            "Cayenne",
            "Neuilly-sur-Seine",
            "Montauban",
            "Chambéry",
            "Niort",
            "Sarcelles",
            "Lorient",
            "Beauvais",
            "Le Blanc-Mesnil",
            "Hyères",
            "Saint-André (La Réunion)|Saint-André",
            "Épinay-sur-Seine",
            "Villejuif",
            "Pantin",
            "Maisons-Alfort",
            "Saint-Quentin",
            "Meaux",
            "Les Abymes",
            "Chelles",
            "La Roche-sur-Yon",
            "Cholet",
            "Narbonne",
            "Fontenay-sous-Bois",
            "Saint-Louis (La Réunion)|Saint-Louis",
            "Vannes",
            "Fréjus",
            "Bondy",
            "Arles",
            "Sartrouville",
            "Clamart",
            "Bobigny",
            "Corbeil-Essonnes",
            "Sevran",
            "Bayonne",
            "Grasse",
            "Massy (Essonne)|Massy",
            "Cagnes-sur-Mer",
            "Vincennes",
            "Saint-Ouen-sur-Seine",
            "Laval (Mayenne)|Laval",
            "Montrouge",
            "Albi",
            "Belfort",
            "Évreux",
            "Martigues",
            "Suresnes",
            "Vaulx-en-Velin",
            "Brive-la-Gaillarde",
            "Charleville-Mézières",
            "Gennevilliers",
            "Saint-Herblain",
            "Saint-Malo",
            "Carcassonne",
            "Saint-Priest",
            "Blois",
            "Salon-de-Provence",
            "Chalon-sur-Saône",
            "Rosny-sous-Bois",
            "Meudon",
            "Aubagne",
            "Saint-Brieuc",
            "Châlons-en-Champagne",
            "Bastia",
            "Puteaux",
            "Livry-Gargan",
            "Choisy-le-Roi",
            "Châteauroux",
            "Saint-Germain-en-Laye",
            "Mantes-la-Jolie",
            "Alfortville",
            "Saint-Laurent-du-Maroni",
            "Valenciennes",
            "Sète",
            "Noisy-le-Sec",
            "Les Sables-d'Olonne (commune nouvelle)|Les Sables-d'Olonne",
            "Istres",
            "Caluire-et-Cuire",
            "Talence",
            "Garges-lès-Gonesse",
            "La Courneuve",
            "Angoulême",
            "Boulogne-sur-Mer",
            "Le Cannet",
            "Bourg-en-Bresse",
            "Wattrelos",
            "Castres",
            "Thionville",
            "Bron",
            "Arras",
            "Gap",
            "Rezé",
            "Tarbes",
            "Compiègne",
            "Melun",
            "Le Lamentin",
            "Draguignan",
            "Alès",
            "Bagneux (Hauts-de-Seine)|Bagneux",
            "Douai",
            "Stains",
            "Marcq-en-Barœul",
            "Gagny",
            "Chartres",
            "Anglet",
            "Colomiers",
            "Montélimar",
            "Saint-Martin-d'Hères",
            "Pontault-Combault",
            "Saint-Benoît (La Réunion)|Saint-Benoît",
            "Saint-Joseph (La Réunion)|Saint-Joseph",
            "Joué-lès-Tours",
            "Villefranche-sur-Saône",
            "Poissy",
            "Châtillon (Hauts-de-Seine)|Châtillon",
            "Villepinte (Seine-Saint-Denis)|Villepinte",
            "Savigny-sur-Orge",
            "Montluçon",
            "Franconville (Val-d'Oise)|Franconville",
            "Bagnolet",
            "Sainte-Geneviève-des-Bois (Essonne)|Sainte-Geneviève-des-Bois",
            "Échirolles",
            "Creil",
            "Saint-Martin (Antilles françaises)|Saint-Martin",
            "Tremblay-en-France",
            "Conflans-Sainte-Honorine",
            "La Ciotat",
            "Saint-Chamond",
            "Saint-Raphaël (Var)|Saint-Raphaël",
            "Thonon-les-Bains",
            "Annemasse",
            "Auxerre",
            "Le Port (La Réunion)|Le Port",
            "Neuilly-sur-Marne",
            "Roanne",
            "Haguenau",
            "Palaiseau",
            "Le Perreux-sur-Marne",
            "Vitrolles (Bouches-du-Rhône)|Vitrolles",
            "Saint-Leu (La Réunion)|Saint-Leu",
            "Athis-Mons",
            "Marignane",
            "Agen",
            "Mâcon",
            "Nevers",
            "Romans-sur-Isère",
            "Six-Fours-les-Plages",
            "Sainte-Marie (La Réunion)|Sainte-Marie",
            "Châtenay-Malabry",
            "Meyzieu",
            "Montigny-le-Bretonneux",
            "La Possession",
            "Villeneuve-Saint-Georges",
            "Villenave-d'Ornon",
            "Trappes",
            "Cambrai",
            "Les Mureaux",
            "Matoury",
            "Koungou",
            "Châtellerault",
            "Nogent-sur-Marne",
            "Dumbéa",
            "Schiltigheim",
            "Houilles",
            "Plaisir (Yvelines)|Plaisir",
            "Épinal",
            "Le Chesnay-Rocquencourt",
            "Vigneux-sur-Seine",
            "L'Haÿ-les-Roses",
            "Chatou",
            "Dreux",
            "Saint-Médard-en-Jalles",
            "Goussainville (Val-d'Oise)|Goussainville",
            "Liévin",
            "Baie-Mahault",
            "Pontoise",
            "Lens (Pas-de-Calais)|Lens",
            "Viry-Châtillon",
            "Rillieux-la-Pape",
            "Charenton-le-Pont",
            "Cachan",
            "Saint-Cloud",
            "Vandœuvre-lès-Nancy",
            "Savigny-le-Temple",
            "Villemomble",
		],
		"Gabon": [
			"Libreville",
			"Port-Gentil",
			"Franceville",
			"Oyem",
			"Moanda",
			"Mouila",
			"Lambaréné",
			"Tchibanga",
			"Koulamoutou",
			"Makokou",
			"Bitam",
			"Tsogni",
			"Gamba",
			"Mounana",
			"Ntoum",
			"Nkan",
			"Lastourville",
			"Okondja",
			"Ndendé",
			"Booué",
			"Fougamou",
			"Ndjolé",
			"Mbigou",
			"Mayumba",
			"Mitzic",
			"Mékambo",
			"Lékoni",
			"Mimongo",
			"Minvoul",
			"Medouneu",
			"Omboué",
			"Cocobeach",
			"Kango",
		],
		"Gambie": [],
		"Géorgie": [],
		"Géorgie du Sud et les îles Sandwich du Sud": [],
		"Ghana": [],
		"Gibraltar": [],
		"Grèce": [],
		"Grenade": [],
		"Groenland": [],
		"Guadeloupe": [],
		"Guam": [],
		"Guatemala": [],
		"Guernesey": [],
		"Guinée": [
			"Conakry",
			"Nzérékoré",
			"Kankan",
			"Kindia",
			"Siguiri",
			"Boké",
			"Kissidougou",
			"Labé",
			"Dubréka",
			"Kamsar",
			"Mamou",
			"Guéckédou",
			"Faranah",
			"Macenta",
			"Fria",
			"Coyah",
			"Lola",
			"Sangaredi",
			"Kérouané",
			"Forécariah",
			"Pita",
			"Dabola",
			"Dinguiraye",
			"Koundara",
			"Télimélé",
			"Kouroussa",
			"Yomou",
			"Beyla",
			"Mandiana",
			"Boffa",
			"Dalaba",
			"Gaoual",
			"Lélouma",
			"Mali",
			"Tougué",
			"Koubia",
		],
		"Guinée équatoriale": [],
		"Guinée-Bissau": [],
		"Guyana": [],
		"Guyane française": [],
		"Haïti": [],
		"Honduras": [],
		"Hongrie": [],
		"Île Bouvet": [],
		"Île Christmas": [],
		"Île Clipperton": [],
		"Île de l'Ascension": [],
		"Île de Man": [],
		"Île Norfolk": [],
		"Îles Åland": [],
		"Îles Caïmans": [],
		"Îles Canaries": [],
		"Îles Cocos - Keeling": [],
		"Îles Cook": [],
		"Îles Féroé": [],
		"Îles Heard et MacDonald": [],
		"Îles Malouines": [],
		"Îles Mariannes du Nord": [],
		"Îles Marshall": [],
		"Îles Mineures Éloignées des États-Unis": [],
		"Îles Salomon": [],
		"Îles Turks et Caïques": [],
		"Îles Vierges britanniques": [],
		"Îles Vierges des États-Unis": [],
		"Inde": [],
		"Indonésie": [],
		"Irak": [],
		"Iran": [],
		"Irlande": [],
		"Islande": [],
		"Israël": [],
		"Italie": [],
		"Jamaïque": [],
		"Japon": [],
		"Jersey": [],
		"Jordanie": [],
		"Kazakhstan": [],
		"Kenya": [],
		"Kirghizistan": [],
		"Kiribati": [],
		"Koweït": [],
		"Laos": [],
		"Lesotho": [],
		"Lettonie": [],
		"Liban": [],
		"Libéria": [],
		"Libye": [],
		"Liechtenstein": [],
		"Lituanie": [],
		"Luxembourg": [],
		"Macédoine": [],
	"Madagascar": [
		"Antananarivo, Tananarive",
		"Toamasina, Tamatave",
		"Antsirabe, Antsirabé",
		"Fianarantsoa",
		"Mahajanga, Majunga",
		"Toliara, Tuléar",
		"Diego-Suarez",
		"Antanifotsy",
		"Ambovombe",
		"Amparafaravola",
		"Tôlanaro",
		"Ambatondrazaka",
		"Mananara Nord",
		"Soavinandriana",
		"Mahanoro",
		"Soanierana Ivongo",
		"Faratsiho",
		"Nosy Varika",
		"Vavatenina",
		"Morondava",
		"Amboasary",
		"Manakara",
		"Antalaha",
		"Ikongo",
		"Manjakandriana",
		"Sambava",
		"Fandriana",
		"Marovoay",
		"Betioky",
		"Ambanja",
		"Ambositra",
	],
		"Malaisie": [],
		"Malawi": [],
		"Maldives": [],
		"Mali": [
			"Bamako",
			"Sikasso",
			"Mopti",
			"Koutiala",
			"Kayes",
			"Ségou",
			"Nioro du Sahel",
			"Niono",
			"Markala",
			"Kolondiéba",
			"Kati",
			"Gao",
			"Kolokani",
			"Ménaka",
			"Bougouni",
			"Niafunké",
			"Tombouctou",
			"Banamba",
			"Macina",
			"Nara",
			"Bafoulabé",
			"San",
			"Koulikoro",
			"Djenné",
			"Sokolo",
			"Yorosso",
			"Kangaba",
			"Kidal",
			"Diré",
			"Goundam",
			"Douentza",
			"Ténenkou",
			"Bandiagara",
			"Kimparana",
			"Kita",
			"Araouane",
			"Taoudeni",
			"Tessalit",
		],
		"Malte": [],
		"Maroc": [],
		"Martinique": [],
		"Maurice": [],
		"Mauritanie": [],
		"Mayotte": [],
		"Mexique": [],
		"Moldavie": [],
		"Monaco": [],
		"Mongolie": [],
		"Monténégro": [],
		"Montserrat": [],
		"Mozambique": [],
		"Myanmar": [],
		"Namibie": [],
		"Nauru": [],
		"Népal": [],
		"Nicaragua": [],
	"Niger": [
		"Niamey",
		"Zinder",
		"Maradi",
		"Tessaoua",
		"Birni N'Konni",
		"Aguié",
		"Tanout",
		"Illéla",
		"Agadez",
		"Tahoua",
		"Madaoua",
		"Tibiri",
		"Arlit",
		"Magaria",
		"Mayahi",
		"Maïné-Soroa",
		"Téra",
		"Dosso",
		"Guidan-Roumdji",
		"Bouza",
		"Loga",
		"Dogondoutchi",
		"Filingué",
		"Ouallam",
		"Gouré",
		"Tchirozérine",
		"Madarounfa",
		"Say",
		"Mirriah",
		"Dakoro",
		"Matamèye",
		"Kéita",
		"Gaya",
		"Birni N'Gaouré",
		"Tillabéri",
		"Diffa",
		"N'Guigmi",
		"Kollo",
		"Abalak",
		"Tchintabaraden",
		"Bilma",
	],
		"Nigéria": [],
		"Niue": [],
		"Norvège": [],
		"Nouvelle-Calédonie": [],
		"Nouvelle-Zélande": [],
		"Oman": [],
		"Ouganda": [],
		"Ouzbékistan": [],
		"Pakistan": [],
		"Palaos": [],
		"Panama": [],
		"Papouasie-Nouvelle-Guinée": [],
		"Paraguay": [],
		"Pays-Bas": [],
		"Pérou": [],
		"Philippines": [],
		"Pitcairn": [],
		"Pologne": [],
		"Polynésie française": [],
		"Porto Rico": [],
		"Portugal": [],
		"Qatar": [],
		"Québec": [
			"Beauceville",
			"Bécancour",
			"Belleterre",
			"Berthierville",
			"Bois-des-Filion",
			"Boisbriand",
			"Boucherville",
			"Lac-Brome",
			"Bromont",
			"Brownsburg-Chatham",
			"Cabano",
			"Candiac",
			"Cap-Chat",
			"Cap-Santé",
			"Carleton-sur-Mer",
			"Causapscal",
			"Châteauguay",
			"Château-Richer",
			"Chibougamau",
			"Cookshire-Eaton",
			"Côte-Saint-Luc",
			"Châteauguayonauguay",
			"Chibougamau",
			"Cookshire-Eaton",
			"Côte-Saint-Luc",
			"Châteauguayonauguay",
			"Dolbeau-Mistassini",
			"Dollard-des-Ormeaux",
			"Dorval",
			"Drummondville",
			"Dunham",
			"East Angus",
			"Fermont",
			"Forestville",
			"Fossambault-sur-le-Lac",
			"Gatineau",
			"Gracefield",
			"L'Île-Cadieux",
			"L'Île-Dorval",
			"L'Île-Perrot",
			"Kingsey Falls",
			"Lac-Delage",
			"Lac-Mégantic",
			"Lac-Saint-Joseph",
			"Lac-Sergent",
			"Lachute",
			"L'Ancienne-Lorette",
			"L'Assomption",
			"La Malbaie",
			"La Pocatière",
			"La Prairie",
			"La Sarre",
			"La Tuque",
			"Lavaltrie",
			"Lebel-sur-Quévillon",
			"L'Île-Perrot",
			"Longueuil",
			"Louiseville",
			"Macamic",
			"Magog",
			"Maniwaki",
			"Marieville",
			"Mascouche",
			"Matagami",
			"Métabetchouan–Lac-à-la-Croix",
			"Métis-sur-Mer",
			"Mirabel (Québec)",
			"Mont-Joli",
			"Mont-Laurier",
			"Mont-Saint-Hilaire",
			"Mont-Tremblant",
			"Montréal",
			"Montréal-Est",
			"Montréal-Ouest",
			"Murdochville",
			"New Richmond",
			"Nicolet",
			"Notre-Dame-de-l'Île-Perrot",
			"Notre-Dame-des-Prairies",
			"Notre-Dame-du-Lac",
			"Otterburn Park",
			"Percé",
			"Pincourt",
			"La Pocatière",
			"Pohénégamook",
			"Pointe-Claire",
			"Pont-Rouge",
			"Port-Cartier",
			"La Prairie",
			"Princeville",
			"Rimouski",
			"Rivière-du-Loup",
			"Rivière-Rouge",
			"Rosemère",
			"Rouyn-Noranda",
			"Sainte-Adèle",
			"Sainte-Agathe-des-Monts",
			"Sainte-Anne-de-Beaupré",
			"Sainte-Anne-de-Bellevue",
			"Sainte-Anne-des-Monts",
			"Sainte-Anne-des-Plaines",
			"Saint-Augustin-de-Desmaures",
			"Saint-Basile-le-Grand",
			"Saint-Bruno-de-Montarville",
			"Sainte-Catherine-de-la-Jacques-Cartier",
			"Saint-Césaire",
			"Saint-Constant",
			"Saint-Gabriel",
			"Saint-Hyacinthe",
			"Saint-Jean-sur-Richelieu",
			"Saint-Joseph-de-Beauce",
			"Saint-Joseph-de-Sorel",
			"Saint-Lin-Laurentides",
			"Saint-Marc-des-Carrières",
			"Sainte-Marguerite-du-Lac-Masson",
			"Sainte-Marthe-sur-le-Lac",
			"Saint-Pamphile",
			"Saint-Pascal",
			"Saint-Pie",
			"Saint-Raymond",
			"Sainte-Thérèse",
			"Saint-Tite",
			"Salaberry-de-Valleyfield",
			"La Sarre",
			"Schefferville",
			"Scotstown",
			"Sept-Îles",
			"Shawinigan",
			"Sherbrooke",
			"Sorel-Tracy",
			"Témiscaming",
			"Terrebonne",
			"Thetford Mines",
			"Trois-Pistoles",
			"Trois-Rivières",
			"La Tuque",
			"Val-d'Or",
			"Vaudreuil-Dorion",
			"Victoriaville",
			"Westmount",
		],
		"R.A.S. chinoise de Hong Kong": [],
		"R.A.S. chinoise de Macao": [],
		"régions éloignées de l’Océanie": [],
		"République centrafricaine": [
			"Bangui",
			"Bimbo",
			"Berbérati",
			"Carnot",
			"Bambari",
			"Bouar",
			"Bria",
			"Bossangoa",
			"Nola",
			"Bangassou",
			"Boda",
			"Sibut",
			"Kaga-Bandoro",
			"Mbaiki",
			"Bozoum",
			"Batangafo",
			"Paoua",
			"Ippy",
			"Bocaranga",
			"Kabo",
			"Alindao",
			"Yaloké",
			"Baoro",
			"Gamboula",
			"Ndélé",
			"Dékoa",
			"Bouca",
			"Grimari",
			"Bossembélé",
			"Kembé",
			"Zémio",
			"Mobaye",
			"Kouango",
			"Baboua",
			"Damara",
			"Birao",
			"Obo",
		],
	"République démocratique du Congo": [
		"Kinshasa",
		"Lubumbashi",
		"Mbuji-Mayi",
		"Kananga",
		"Kisangani",
		"Bukavu",
		"Tshikapa",
		"Kolwezi",
		"Likasi",
		"Goma",
		"Kikwit",
		"Uvira",
		"Bunia",
		"Kalemie",
		"Mbandaka",
		"Matadi",
		"Kabinda",
		"Butembo",
		"Baraka",
		"Mwene-Ditu",
		"Isiro",
		"Kindu",
		"Boma",
		"Kamina",
		"Gandajika",
		"Bandundu",
		"Gemena",
		"Kipushi",
		"Bumba",
		"Mbanza-Ngungu",
	],
		"République dominicaine": [],
		"République tchèque": [],
		"Réunion": [],
		"Roumanie": [],
		"Royaume-Uni": [],
		"Russie": [],
		"Rwanda": [
			"Kigali",
			"Butare",
			"Gitarama",
			"Ruhengeri",
			"Gisenyi",
			"Byumba",
			"Cyangugu",
			"Nyanza",
			"Kabuga",
			"Ruhango",
			"Rwamagana",
			"Kibuye",
			"Kibungo",
			"Gikongoro",
			"Umutara",
		],
		"Sahara occidental": [],
		"Saint-Barthélémy": [],
		"Saint-Kitts-et-Nevis": [],
		"Saint-Marin": [],
		"Saint-Martin": [],
		"Saint-Pierre-et-Miquelon": [],
		"Saint-Vincent-et-les Grenadines": [],
		"Sainte-Hélène": [],
		"Sainte-Lucie": [],
		"Samoa": [],
		"Samoa américaines": [],
		"Sao Tomé-et-Principe": [],
	"Sénégal": [
		"Dakar",
		"Pikine",
		"Touba",
		"Guédiawaye",
		"Thiès",
		"Kaolack",
		"Mbour",
		"Saint-Louis",
		"Rufisque",
		"Ziguinchor",
		"Diourbel",
		"Louga",
		"Tambacounda",
		"Mbacké",
		"Kolda",
		"Richard-Toll",
		"Bargny",
		"Tivaouane",
		"Joal-Fadiouth",
		"Dahra",
		"Kaffrine",
		"Bignona",
		"Fatick",
		"Vélingara",
		"Bambey",
		"Sébikhotane",
		"Dagana",
		"Sédhiou",
		"Nguékhokh",
		"Diawara",
		"Kédougou",
		"Pout",
		"Kayar",
		"Matam",
		"Meckhe",
		"Nioro du Rip",
		"Ourossogui",
		"Kébémer",
		"Ndioum",
		"Koungheul",
		"Guinguinéo",
		"Linguère",
		"Khombole",
		"Bakel",
		"Sokone",
		"Diamniadio",
		"Mboro",
		"Thiadiaye",
		"Goudomp",
		"Podor",
		"Gossas",
		"Kanel",
		"Rosso",
		"Ndoffane",
		"Gandiaye",
	],
		"Serbie": [],
		"Serbie-et-Monténégro": [],
		"Seychelles": [
			"Moroni",
			"Mutsamudu",
			"Domoni",
			"Fomboni",
			"Tsembéhou",
			"Ongodjou",
			"Sima",
			"Ouani",
			"Mirontsi",
			"Adda Daouéni",
			"Bazmini",
			"Koni Djodjo",
			"Moya",
			"Iconi",
			"Ounkazi",
			"Dindri",
			"Ngandzalé",
			"Mbéni",
			"Mitsamiouli",
			"Barakani",
			"Mbambao Mtsanga",
			"Chandra",
			"Ouellah Hamahamet",
			"Mramani",
			"Mrémani",
			"Koki",
			"Jimlimi",
			"Mvouni",
			"Tsidjé",
			"Foumbouni",
			"Nkourani ya Sima",
			"Magnassini",
			"Mitsoudjé-Troumbeni",
			"Dembéni",
		],
		"Sierra Leone": [],
		"Singapour": [],
		"Slovaquie": [],
		"Slovénie": [],
		"Somalie": [],
		"Soudan": [],
		"Sri Lanka": [],
		"Suède": [],
		"Suisse": [
            "Zurich",
			"Genève",
			"Bâle",
			"Lausanne",
			"Berne",
			"Winterthour",
			"Lucerne",
			"Saint-Gall",
			"Lugano",
			"Bienne",
			"Thoune",
			"Bellinzone",
			"Köniz",
			"La Chaux-de-Fonds",
			"Fribourg (ville suisse)|Fribourg",
			"Schaffhouse",
			"Vernier (Genève)|Vernier",
			"Coire",
			"Uster",
			"Sion (Valais)|Sion",
			"Neuchâtel",
			"Lancy",
			"Emmen (Lucerne)|Emmen",
			"Yverdon-les-Bains",
			"Zoug (ville)|Zoug",
			"Dübendorf",
			"Kriens",
			"Dietikon",
			"Rapperswil-Jona",
			"Montreux",
			"Vevey",
			"Frauenfeld",
			"Wetzikon",
			"Baar (Zoug)|Baar",
			"Wil (Saint-Gall)|Wil",
			"Meyrin",
			"Bulle (Fribourg)|Bulle",
			"Horgen",
			"Carouge",
			"Wädenswil",
			"Kreuzlingen",
			"Riehen",
			"Allschwil",
			"Aarau",
			"Wettingen",
			"Renens",
			"Nyon",
			"Vevey",
			"Montreux",
			"Bülach",
			"Opfikon",
			"Baden (Argovie)|Baden",
			"Reinach (Bâle-Campagne)|Reinach",
			"Kloten",
			"Onex (Genève)|Onex",
			"Schlieren",
			"Adliswil",
			"Volketswil",
			"Regensdorf",
			"Olten",
			"Glaris Nord",
			"Gossau (Saint-Gall)|Gossau",
			"Martigny",
			"Pully",
			"Thalwil",
			"Muttenz",
			"Monthey",
			"Ostermundigen",
			"Granges (Soleure)|Granges",
			"Sierre",
			"Illnau-Effretikon",
			"Soleure",
			"Pratteln",
			"Berthoud",
			"Cham (Zoug)|Cham",
			"Freienbach",
			"Locarno",
			"Wallisellen",
			"Morges",
			"Steffisburg",
			"Wohlen (Argovie)|Wohlen",
			"Herisau",
			"Langenthal",
			"Binningen",
			"Einsiedeln",
			"Mendrisio",
			"Schwytz (ville)|Schwytz",
			"Lyss",
			"Arbon (Thurgovie)|Arbon",
			"Stäfa",
			"Liestal",
			"Küsnacht",
			"Thônex",
			"Horw",
			"Meilen",
			"Oftringen",
			"Versoix",
			"Richterswil",
			"Amriswil",
			"Rheinfelden (Argovie)|Rheinfelden",
			"Ebikon",
			"Brigue-Glis",
			"Muri bei Bern",
			"Gland (Vaud)|Gland",
			"Uzwil",
			"Zollikon",
			"Spiez",
			"Delémont",
			"Buchs (Saint-Gall)|Buchs",
			"Glaris Centre",
			"Écublens (Vaud)|Écublens",
			"Münchenstein",
			"Le Grand-Saconnex",
			"Villars-sur-Glâne",
			"Rüti (Zurich)|Rüti",
			"Prilly",
			"Münsingen (Berne)|Münsingen",
			"Affoltern am Albis",
			"Pfäffikon (Zurich)|Pfäffikon",
			"Arth",
			"Chêne-Bougeries",
			"La Tour-de-Peilz",
			"Montreux",
			"Bassersdorf",
			"Veyrier",
			"Spreitenbach",
			"Belp",
			"Zofingue",
			"Worb",
			"Altstätten",
			"Ittigen",
			"Weinfelden",
			"Oberwil (Bâle-Campagne)|Oberwil",
			"Brugg",
			"Hinwil",
			"Davos",
			"Möhlin",
			"Männedorf",
			"Romanshorn",
			"Plan-les-Ouates",
			"Birsfelden",
			"Flawil",
			"La Chaux-de-Fonds",
			"Neuhausen am Rheinfall",
			"Risch-Rotkreuz",
			"Aesch (Bâle-Campagne)|Aesch",
			"Zollikofen",
			"Sarnen",
			"Münchenbuchsee",
			"Aigle (Vaud)|Aigle",
			"Suhr",
			"Steinhausen (Zoug)|Steinhausen",
			"Urdorf",
			"Sursee",
			"Lenzbourg",
			"Payerne",
			"Rorschach (Saint-Gall)|Rorschach",
			"Arlesheim",
			"Altdorf (Uri)|Altdorf",
			"Zuchwil",
			"Stans",
			"Chiasso",
			"Bussigny",
			"Morat",
			"Crissier",
			"Viège",
			"Moutier",
			"Porrentruy",
			"Peseux (Neuchâtel)|Peseux",
			"Appenzell (district)|Appenzell",
			"Zermatt",
			"Interlaken",
			"Saint-Moritz",
			"La Neuveville",
			"Arosa",
        ],
		"Suriname": [],
		"Svalbard et Île Jan Mayen": [],
		"Swaziland": [],
		"Syrie": [],
		"Tadjikistan": [],
		"Taïwan": [],
		"Tanzanie": [],
		"Tchad": [
		"N'Djaména",
		"Moundou",
		"Sarh",
		"Abéché",
		"Faya-Largeau",
		"Koumra",
		"Kélo",
		"Mongo",
		"Pala",
		"Am Timan",
		"Ati",
		"Bongor",
		"Doba",
		"Mao",
		"Oum Hadjer",
		"Moussoro",
		"Bitkine",
		"Biltine",
		"Massaguet",
		"Dourbali",
		"Laï",
		"Léré",
		"Kyabé",
		"Massakory",
		"Bokoro",
		"Bousso",
		"Benoye",
		"Bébédjia",
		"Adré",
		"Ngama",
		"Béré",
		"Fianga",
		"Bol",
		"Moïssala",
		"Guelendeng",
		"Goundi",
		"Gounou Gaya",
		"Baïbokoum",
		"Aozou",
		"Beinamar",
		"Melfi",
		"Béboto",
		"Massenya",
		],
	"Terres australes françaises": [],
	"Territoire britannique de l'océan Indien": [],
	"Territoire palestinien": [],
	"Thaïlande": [],
	"Timor oriental": [],
	"Togo": [
		"Lomé",
		"Sokodé",
		"Kara",
		"Kpalimé",
		"Atakpamé",
		"Bassar",
		"Tsévié",
		"Aného",
		"Mango",
		"Dapaong",
		"Tchamba",
		"Niamtougou",
		"Bafilo",
		"Notsé",
		"Sotouboua",
		"Vogan",
		"Badou",
		"Biankouri",
		"Tabligbo",
		"Kandé",
		"Amlamé",
		"Galangachi",
		"Kpagouda",
	],
		"Tokelau": [],
		"Tonga": [],
		"Trinité-et-Tobago": [],
		"Tristan da Cunha": [],
		"Tunisie": [],
		"Turkménistan": [],
		"Turquie": [],
		"Tuvalu": [],
		"Ukraine": [],
		"Union européenne": [],
		"Uruguay": [],
		"Vanuatu": [],
		"Venezuela": [],
		"Viêt Nam": [],
		"Wallis-et-Futuna": [],
		"Yémen": [],
		"Zambie": [],
		"Zimbabwe": [],
};

export default Countries;
